name: Deploy to Local

on:
  push:
    branches:
      - main

jobs:
  deploy_to_local:
    runs-on: [dgx-2-2]

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build --build-arg VITE_BACKEND_BASE_URL=${{ secrets.VITE_BACKEND_BASE_URL }} -t prepaire_chatbot:dev .

      - name: Remove old service (optional)
        run: |
          docker service rm prepaire_chatbot || true

      - name: Deploy frontend to Docker Swarm
        run: |
          docker service create \
            --name prepaire_chatbot \
            --replicas 1 \  # Increase if needed
            --publish published=3006,target=3000 \
            --env VITE_OPENAI_API_KEY="${{ secrets.VITE_OPENAI_API_KEY }}" \
            --env VITE_OLLAMA_URL="${{ secrets.VITE_OLLAMA_URL }}" \
            --env VITE_BACKEND_BASE_URL="${{ secrets.VITE_BACKEND_BASE_URL }}" \
            prepaire_chatbot:dev

    environment:
      name: development
